version: '3.8'
name: neo4j-compose
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/T3stT3st!  # Default username and password (change it for production)
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_logs_debug_level=INFO
    networks:
      - neo4j-net
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

networks:
  neo4j-net:
    driver: bridge

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local